pipeline_directory: /full/path/to/cloned/repo

# Sample file specifies sample names and names of files containing sample reads
# Format: Tab-delimited, two columns
# sample_name  reads_R1R2file
# See example (samp_file.txt) in the testing folder
sample_file: /full/path/to/cloned/repo/test_data/sample_file.txt

# In which directory should results be outputted?
outdir: /full/path/to/cloned/repo/test_data


# The value setting
threads: 8 # see usage instructions - can increase if you have more threads available
IDENTITY: 90 # diamond balst used identity
COVERAGE: 80 # diamond balst used coverage
MARKER_COVERAGE: 0.7 # 
MARKER_RATIO: 0.5 #
 
